"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-12 21:33:15.613740
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_key', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('hq_country', sa.String(length=2), nullable=True),
    sa.Column('headcount_band', sa.String(length=32), nullable=True),
    sa.Column('blocklisted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_company_key'), 'company', ['company_key'], unique=True)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('countries_eligible', postgresql.ARRAY(sa.String(length=8)), nullable=False),
    sa.Column('min_overlap_hours', sa.Integer(), nullable=False),
    sa.Column('entity_status', sa.String(length=32), nullable=False),
    sa.Column('eor_ready', sa.Boolean(), nullable=False),
    sa.Column('rate_floor_hourly', sa.Float(), nullable=True),
    sa.Column('rate_target_hourly', sa.Float(), nullable=True),
    sa.Column('comp_floor_annual', sa.Float(), nullable=True),
    sa.Column('comp_currency', sa.String(length=8), nullable=False),
    sa.Column('track_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weekly_send_cap', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('family', sa.String(length=40), nullable=False),
    sa.Column('legal_tier', sa.SmallInteger(), nullable=False),
    sa.Column('tracks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('company_hint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cadence_minutes', sa.Integer(), nullable=False),
    sa.Column('rate_limit_rps', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_discovered', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_key'), 'source', ['key'], unique=True)
    op.create_table('company_ats_slug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('ats', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('discovered_from', sa.String(length=80), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jobs_last_seen', sa.Integer(), nullable=True),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ats', 'slug', name='uq_ats_slug')
    )
    op.create_index(op.f('ix_company_ats_slug_ats'), 'company_ats_slug', ['ats'], unique=False)
    op.create_table('job_cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_hash', sa.String(length=64), nullable=False),
    sa.Column('canonical_posting_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title_key', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('fan_out', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recurrence_months', sa.Integer(), nullable=False),
    sa.Column('tracks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_cluster_identity_hash'), 'job_cluster', ['identity_hash'], unique=True)
    op.create_index(op.f('ix_job_cluster_status'), 'job_cluster', ['status'], unique=False)
    op.create_table('profile_fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verifiable_by', sa.Text(), nullable=True),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_fact_key'), 'profile_fact', ['key'], unique=False)
    op.create_table('profile_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(length=16), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('target_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('must_have_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nice_to_have_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exclude_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_variant_track'), 'profile_variant', ['track'], unique=False)
    op.create_table('source_prior',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(length=16), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('sends', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'track', name='uq_prior_source_track')
    )
    op.create_table('source_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('items_changed', sa.Integer(), nullable=False),
    sa.Column('bytes_fetched', sa.Integer(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('schema_drift_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_run_source_id'), 'source_run', ['source_id'], unique=False)
    op.create_table('job_posting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('title_key', sa.String(length=400), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('desc_hash', sa.String(length=64), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('apply_url_canonical', sa.Text(), nullable=True),
    sa.Column('apply_url_hash', sa.String(length=64), nullable=True),
    sa.Column('employment_type', sa.String(length=64), nullable=True),
    sa.Column('seniority', sa.String(length=64), nullable=True),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('countries_allowed', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('timezones_allowed', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('remote_policy', sa.String(length=24), nullable=False),
    sa.Column('comp_min', sa.Float(), nullable=True),
    sa.Column('comp_max', sa.Float(), nullable=True),
    sa.Column('comp_currency', sa.String(length=8), nullable=True),
    sa.Column('comp_period', sa.String(length=16), nullable=True),
    sa.Column('first_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('form_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('liveness_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('liveness_ok', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['job_cluster.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_source_external')
    )
    op.create_index(op.f('ix_job_posting_cluster_id'), 'job_posting', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_job_posting_source_id'), 'job_posting', ['source_id'], unique=False)
    op.create_index('ix_posting_apply_hash', 'job_posting', ['apply_url_hash'], unique=False)
    op.create_index('ix_posting_desc_hash', 'job_posting', ['desc_hash'], unique=False)
    op.create_index('ix_posting_first_published', 'job_posting', ['first_published_at'], unique=False)
    op.create_table('raw_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_run_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_run_id'], ['source_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_document_content_hash'), 'raw_document', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_document_expires_at'), 'raw_document', ['expires_at'], unique=False)
    op.create_index(op.f('ix_raw_document_source_id'), 'raw_document', ['source_id'], unique=False)
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(length=16), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('semantic', sa.Float(), nullable=False),
    sa.Column('skill_coverage', sa.Float(), nullable=False),
    sa.Column('title_fit', sa.Float(), nullable=False),
    sa.Column('freshness', sa.Float(), nullable=False),
    sa.Column('comp_fit', sa.Float(), nullable=False),
    sa.Column('source_prior', sa.Float(), nullable=False),
    sa.Column('ghost_risk', sa.Float(), nullable=False),
    sa.Column('crowding', sa.Float(), nullable=False),
    sa.Column('warm_path', sa.Float(), nullable=False),
    sa.Column('s_fast', sa.Float(), nullable=False),
    sa.Column('llm_model', sa.String(length=120), nullable=True),
    sa.Column('llm_fit', sa.Float(), nullable=True),
    sa.Column('llm_verdict', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('injection_suspected', sa.Boolean(), nullable=False),
    sa.Column('fit', sa.Float(), nullable=False),
    sa.Column('trust', sa.Float(), nullable=False),
    sa.Column('reach', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explain', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['job_cluster.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'track', name='uq_score_cluster_track')
    )
    op.create_index(op.f('ix_score_cluster_id'), 'score', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_score_priority'), 'score', ['priority'], unique=False)
    op.create_index(op.f('ix_score_s_fast'), 'score', ['s_fast'], unique=False)
    op.create_table('skip_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['job_cluster.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skip_feedback_reason_code'), 'skip_feedback', ['reason_code'], unique=False)
    op.create_table('draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=True),
    sa.Column('template', sa.String(length=32), nullable=False),
    sa.Column('track', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['job_cluster.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['score_id'], ['score.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_cluster_id'), 'draft', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_draft_status'), 'draft', ['status'], unique=False)
    op.create_table('eligibility_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('matched_pattern', sa.Text(), nullable=True),
    sa.Column('matched_span', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_posting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_flag_code'), 'eligibility_flag', ['code'], unique=False)
    op.create_index(op.f('ix_eligibility_flag_job_posting_id'), 'eligibility_flag', ['job_posting_id'], unique=False)
    op.create_table('draft_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('paragraphs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fact_keys', postgresql.ARRAY(sa.String(length=16)), nullable=True),
    sa.Column('jd_hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('open_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('passed_all_checks', sa.Boolean(), nullable=False),
    sa.Column('edited_by_human', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_version_draft_id'), 'draft_version', ['draft_id'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('draft_version_id', sa.Integer(), nullable=True),
    sa.Column('track', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('stage_entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_quoted', sa.Float(), nullable=True),
    sa.Column('follow_up_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('presumed_dead_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('outcome_detail', sa.Text(), nullable=True),
    sa.Column('replied', sa.Boolean(), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hours_to_reply', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['job_cluster.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_version_id'], ['draft_version.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_cluster_id'), 'application', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_application_follow_up_due_at'), 'application', ['follow_up_due_at'], unique=False)
    op.create_index(op.f('ix_application_stage'), 'application', ['stage'], unique=False)
    op.create_table('approval_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_version_id', sa.Integer(), nullable=False),
    sa.Column('token_hmac', sa.String(length=64), nullable=False),
    sa.Column('body_sha256', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_via', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['draft_version_id'], ['draft_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hmac')
    )
    op.create_index(op.f('ix_approval_token_draft_version_id'), 'approval_token', ['draft_version_id'], unique=False)
    op.create_table('draft_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_version_id', sa.Integer(), nullable=False),
    sa.Column('check', sa.String(length=32), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['draft_version_id'], ['draft_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_check_draft_version_id'), 'draft_check', ['draft_version_id'], unique=False)
    op.create_table('application_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(length=24), nullable=True),
    sa.Column('to_stage', sa.String(length=24), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_event_application_id'), 'application_event', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_event_application_id'), table_name='application_event')
    op.drop_table('application_event')
    op.drop_index(op.f('ix_draft_check_draft_version_id'), table_name='draft_check')
    op.drop_table('draft_check')
    op.drop_index(op.f('ix_approval_token_draft_version_id'), table_name='approval_token')
    op.drop_table('approval_token')
    op.drop_index(op.f('ix_application_stage'), table_name='application')
    op.drop_index(op.f('ix_application_follow_up_due_at'), table_name='application')
    op.drop_index(op.f('ix_application_cluster_id'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_draft_version_draft_id'), table_name='draft_version')
    op.drop_table('draft_version')
    op.drop_index(op.f('ix_eligibility_flag_job_posting_id'), table_name='eligibility_flag')
    op.drop_index(op.f('ix_eligibility_flag_code'), table_name='eligibility_flag')
    op.drop_table('eligibility_flag')
    op.drop_index(op.f('ix_draft_status'), table_name='draft')
    op.drop_index(op.f('ix_draft_cluster_id'), table_name='draft')
    op.drop_table('draft')
    op.drop_index(op.f('ix_skip_feedback_reason_code'), table_name='skip_feedback')
    op.drop_table('skip_feedback')
    op.drop_index(op.f('ix_score_s_fast'), table_name='score')
    op.drop_index(op.f('ix_score_priority'), table_name='score')
    op.drop_index(op.f('ix_score_cluster_id'), table_name='score')
    op.drop_table('score')
    op.drop_index(op.f('ix_raw_document_source_id'), table_name='raw_document')
    op.drop_index(op.f('ix_raw_document_expires_at'), table_name='raw_document')
    op.drop_index(op.f('ix_raw_document_content_hash'), table_name='raw_document')
    op.drop_table('raw_document')
    op.drop_index('ix_posting_first_published', table_name='job_posting')
    op.drop_index('ix_posting_desc_hash', table_name='job_posting')
    op.drop_index('ix_posting_apply_hash', table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_source_id'), table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_cluster_id'), table_name='job_posting')
    op.drop_table('job_posting')
    op.drop_index(op.f('ix_source_run_source_id'), table_name='source_run')
    op.drop_table('source_run')
    op.drop_table('source_prior')
    op.drop_index(op.f('ix_profile_variant_track'), table_name='profile_variant')
    op.drop_table('profile_variant')
    op.drop_index(op.f('ix_profile_fact_key'), table_name='profile_fact')
    op.drop_table('profile_fact')
    op.drop_index(op.f('ix_job_cluster_status'), table_name='job_cluster')
    op.drop_index(op.f('ix_job_cluster_identity_hash'), table_name='job_cluster')
    op.drop_table('job_cluster')
    op.drop_index(op.f('ix_company_ats_slug_ats'), table_name='company_ats_slug')
    op.drop_table('company_ats_slug')
    op.drop_index(op.f('ix_source_key'), table_name='source')
    op.drop_table('source')
    op.drop_table('setting')
    op.drop_table('profile')
    op.drop_index(op.f('ix_company_company_key'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
