"""cluster notified_at

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-15 15:44:10.032140
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_cluster', sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_cluster', 'notified_at')
    # ### end Alembic commands ###
